language: node_js
node_js:
- stable
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install -g mocha node-gyp
- npm install
script:
- npm test
- npm run coverage
