language: node_js
node_js:
- stable
sudo: false
services:
  - mongodb
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install -g mocha node-gyp
- npm install
before_script:
  - sleep 30
  - mongo highway --eval 'db.createCollection("users");'
script:
- npm test
- npm run coverage
